id: P008174
initial_creation_type: ocr
created_at: 28/03/2020
last_modified_at: 25/11/2021
source_metadata:
  id: bdr:W4CZ74207
  title: བཻ་ཌཱུརྱ་དཀར་པོ།
  author: ''
  volumes:
    e685cc7495304036b37901bbdf366940:
      image_group_id: I4CZ74285
      title: ''
      volume_number: 1
      total_pages: 1278
      base_file: v001.txt
