id: I410D1808
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-28T10:42:02+00:00'
last_modified: '2022-06-09T05:00:54.901607+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W4CZ74207
  title: བཻ་ཌཱུརྱ་དཀར་པོ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: true
  base:
    543A:
      image_group_id: I4CZ74285
      title: ''
      total_pages: 1278
      order: 1
      base_file: 543A.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
